### ISSUE TITLE
Installation prompt failed through comfui manager

### ISSUE THREAD

**Issue by HHUtian** [niknah/quick-connections#18]
The installation prompt failed through the comfui manager. It was installed by direct download, but the plug-in could not be seen in the manager. How to solve this problem?

**Comment by HHUtian** [comment]
> 安装或启动 ComfyUI。然后在此处复制并粘贴日志。

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\01-01HH\comfyui-Nenly\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[]
[]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json[ComfyUI-Manager] Due to a network error, switching to local mode.
=> extension-node-map.json
=> Cannot connect to host raw.githubusercontent.com:443 ssl:default [getaddrinfo failed]
FETCH DATA from: C:\01-01HH\comfyui-Nenly\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json[ComfyUI-Manager] Due to a network error, switching to local mode.
=> custom-node-list.json
=> Cannot connect to host raw.githubusercontent.com:443 ssl:default [getaddrinfo failed]
FETCH DATA from: C:\01-01HH\comfyui-Nenly\ComfyUI\custom_nodes\ComfyUI-Manager\custom-node-list.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json[ComfyUI-Manager] Due to a network error, switching to local mode.
=> github-stats.json
=> Cannot connect to host raw.githubusercontent.com:443 ssl:default [getaddrinfo failed]
FETCH DATA from: C:\01-01HH\comfyui-Nenly\ComfyUI\custom_nodes\ComfyUI-Manager\github-stats.json [DONE]
FETCH DATA from: C:\01-01HH\comfyui-Nenly\ComfyUI\custom_nodes\ComfyUI-Manager\custom-node-list.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json[ComfyUI-Manager] Due to a network error, switching to local mode.
=> custom-node-list.json
=> Cannot connect to host raw.githubusercontent.com:443 ssl:default [getaddrinfo failed]
FETCH DATA from: C:\01-01HH\comfyui-Nenly\ComfyUI\custom_nodes\ComfyUI-Manager\custom-node-list.json [DONE]
Install custom node 'Quick Connections'
Install: ['https://github.com/niknah/quick-connections']
Download: git clone 'https://github.com/niknah/quick-connections'
[!]
0it [00:00, ?it/s]Cmd('git') failed due to: exit code(128)
0it [00:21, ?it/s]  cmdline: git clone -v --recursive --progress -- https://github.com/niknah/quick-connections C:\01-01HH\comfyui-Nenly\ComfyUI\custom_nodes\quick-connections
Error handling request
Traceback (most recent call last):
  File "C:\01-01HH\comfyui-Nenly\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1025, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncio\base_events.py", line 1086, in create_connection
  File "asyncio\base_events.py", line 1070, in create_connection
  File "asyncio\base_events.py", line 974, in _connect_sock
  File "asyncio\proactor_events.py", line 726, in sock_connect
  File "asyncio\windows_events.py", line 854, in _poll
  File "asyncio\windows_events.py", line 641, in finish_connect
OSError: [WinError 121] 信号灯超时时间已到

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\01-01HH\comfyui-Nenly\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\01-01HH\comfyui-Nenly\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\01-01HH\comfyui-Nenly\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\01-01HH\comfyui-Nenly\ComfyUI\server.py", line 64, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\01-01HH\comfyui-Nenly\ComfyUI\server.py", line 142, in origin_only_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\01-01HH\comfyui-Nenly\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1200, in get_notice
    async with session.get(f"https://{url}{path}") as response:
  File "C:\01-01HH\comfyui-Nenly\python_embeded\Lib\site-packages\aiohttp\client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\01-01HH\comfyui-Nenly\python_embeded\Lib\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\01-01HH\comfyui-Nenly\python_embeded\Lib\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\01-01HH\comfyui-Nenly\python_embeded\Lib\site-packages\aiohttp\connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\01-01HH\comfyui-Nenly\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1257, in _create_direct_connection
    raise last_exc
  File "C:\01-01HH\comfyui-Nenly\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1226, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\01-01HH\comfyui-Nenly\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1033, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host github.com:443 ssl:default [信号灯超时时间已到]
FETCH DATA from: C:\01-01HH\comfyui-Nenly\ComfyUI\custom_nodes\ComfyUI-Manager\custom-node-list.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json[ComfyUI-Manager] Due to a network error, switching to local mode.
=> custom-node-list.json
=> Cannot connect to host raw.githubusercontent.com:443 ssl:default [getaddrinfo failed]
FETCH DATA from: C:\01-01HH\comfyui-Nenly\ComfyUI\custom_nodes\ComfyUI-Manager\custom-node-list.json [DONE]
Install custom node 'Quick Connections'
Install: ['https://github.com/niknah/quick-connections']
Download: git clone 'https://github.com/niknah/quick-connections'
[!]
0it [00:00, ?it/s]Cmd('git') failed due to: exit code(128)
0it [00:21, ?it/s]  cmdline: git clone -v --recursive --progress -- https://github.com/niknah/quick-connections C:\01-01HH\comfyui-Nenly\ComfyUI\custom_nodes\quick-connections
